"""empty message

Revision ID: 28e4bbff2cf1
Revises: 
Create Date: 2019-03-04 19:29:10.002805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28e4bbff2cf1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('price', sa.Integer(), nullable=True))
    op.drop_column('Products', 'harga')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('harga', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('Products', 'price')
    # ### end Alembic commands ###
